### PR TITLE
Fix for lime build won't read .build if git is present

### PR DESCRIPTION
**Pull request by giuppe**
This fixes issue #1409.

### CODE REVIEW

**Comment by joshtynjala** [comment]
This change causes the following exception when I run `lime rebuild tools`:

```
Called from ? line 1
Called from CommandLineTools.hx line 1895
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 390
Called from CommandLineTools.hx line 1888
Called from CommandLineTools.hx line 1250
Called from hxp/StringTools.hx line 457
Called from /usr/local/lib/haxe/std/StringTools.hx line 241
Uncaught exception - Invalid field access : length
```

The call to `StringTools.startsWith()` now fails when `buildNumber` is null.

**Comment by joshtynjala** [comment]
I reverted this commit for now so that it doesn't prevent anyone from working on Lime.

**Comment by giuppe** [comment]
I understand why this happens: if `buildNumber` is null, it can't be a string.

So the working code should first check if `buildNumber` is null (and nothing else). 
Then, if it's null, should check for the `.build` file. 
Then, if EITHER it's still null OR it's a string that starts with "git", should calculate the git build number.

The fix should not be about changing OR into AND (that was wrong) but about changing the order of the `if`s
I'm preparing a PR with the fix.

**Comment by joshtynjala** [comment]
Yeah, that sounds like the right way to do it to me.

**Comment by player-03** [comment]
Sounds good.

It's worth noting that git/svn users may have old .build files lying around, so we should mention this in the release notes. "If your build number changes unexpectedly, try removing the .build file from your output folder."

**Pull request merged**
