### PR TITLE
Add a `if (__backend != null)` statement

### PR DESCRIPTION
**Pull request by Cheemsandfriends**
Hello,
So while trying to add a pitch setting more nicely in the PR number #1510, It seems that when you get and set the pitch, it crashes. So basically meant that the other ones, like the loop, gain etc. won't work because the pitch didn't work without it.

This adds the `if (__backend != null)` in case you play the music at the beginning of everything and you want to set some things while it loads and stuff

### CODE REVIEW

**Comment by Cheemsandfriends** [comment]
Srry if this is a shitty solution.
I actually don't know why the backend brings null and the game crashes if you set something so I made the easiest solution imo. even tho it isn't optimal

**Comment by Cheemsandfriends** [comment]
I closed it cos of the comment of @player-03 lol

**Comment by player-03** [comment]
Ah, so it really does crash. (I thought it was just hypothetical.) Anyway, as I said in that comment, we should figure out why it's null, not just hide the error.

Can you post your test code?

**Comment by Cheemsandfriends** [comment]
@player-03, Nvm, I think that I know why it crashed before. I'll post A thingy with a review post and why I think it crashes

**Pull request closed without merging**
